baseURL = "http://short-thoughts.ml"
title = "Short Toughts"
theme = "refined"

[Params]
  tagline = "My random thoughts"

  # Go date formats: https://golang.org/pkg/time/#pkg-constants
  dateform = "Mon Jan 2, 2006"

  # Set favicons to true only if the following files are present in the project assets/ dir:
  # - safari-pinned-tab.svg
  # - manifest.json
  # - favicon-16x16.png
  # - favicon-32x32.png
  # - apple-touch-icon.png
  favicons = false

  themecolorbase = "yellow"
